name: app_stepmate
description: Indoor Navigation for Visually Impaired
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.3.0
  flutter_blue_plus: ^1.31.1
  sensors_plus: ^7.0.0
  flutter_tts: ^4.0.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.0.0
  firebase_core: ^3.15.2
  firebase_database: ^11.0.0
  google_fonts: ^6.2.1
  vibration: ^3.1.5
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true